config/routes.rb
BankAccountx::Engine.routes.draw do

  resources :accounts
end

app/models/bank_accountx/account.rb
module BankAccountx
  class Account < ActiveRecord::Base
    attr_accessible :account_name, :account_num, :bank_name, :brief_note, :active, :last_updated_by_id, :as => :role_new
    attr_accessible :account_name, :account_num, :bank_name, :brief_note, :active, :last_updated_by_id, :as => :role_update
    
    belongs_to :contract, :class_name => 'Contractx::Contract'
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    
    validates_presence_of :account_name, :account_num, :bank_name
    validates :account_num, :uniqueness => {:case_sensitive => false}
  end
end

app/controllers/bank_accountx/accounts_controller.rb
require_dependency "bank_accountx/application_controller"

module BankAccountx
  class AccountsController < ApplicationController
    before_filter :require_signin
    before_filter :require_employee
    
    def index
      @title = 'Bank Accounts'
      if has_index_right?("bank_accountx_accounts")
        if has_create_right?("bank_accountx_accounts")
          @accounts = BankAccountx::Account.order("id DESC")
        else
          @accounts = BankAccountx::Account.where(:active => true).order("id DESC")
        end
      else
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Insufficient Right!")  
      end
    end
  
    def new
      @title = 'New Bank Account'
      if has_create_right?("bank_accountx_accounts")
        @account = BankAccountx::Account.new(params[:account], :as => :role_new)
      else
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Insufficient Right!")  
      end       
    end
  
    def create
      if has_create_right?("bank_accountx_accounts")
        @account = BankAccountx::Account.new(params[:account], :as => :role_new)
        @account.last_updated_by_id = session[:user_id]
        if @account.save
          redirect_to accounts_path, :notice => "Bank Account Saved!"
        else
          flash.now[:error] = 'Data Error. Not Saved!'
          render 'new'
        end
      end
    end
  
    def edit
      @title = 'Update Bank Account'
      if has_update_right?("bank_accountx_accounts")
        @account = BankAccountx::Account.find_by_id(params[:id])
      else
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Insufficient Right!") 
      end
    end
  
    def update
      if has_update_right?("bank_accountx_accounts")
        @account = BankAccountx::Account.find_by_id(params[:id])
        if @account.update_attributes(params[:account], :as => :role_update)
          redirect_to accounts_path, :notice => "Bank Account Updated!"
        else
          flash.now[:error] = 'Data Error. Not Updated!'
          render 'edit'
        end
      end
    end
  end
end

app/controllers/bank_accountx/application_controller.rb
# encoding: utf-8
module BankAccountx
  class ApplicationController < ActionController::Base
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UserPrivilegeHelper
    include Authentify::UsersHelper
    
    helper_method :has_index_right?, :has_create_right?, :has_update_right?, :has_show_right?, :has_destroy_right?, 
                  :has_activate_right?, :yes_no_cn
    
    def yes_no_cn
      [['是',true ],['否', false]]
    end
  
    def has_index_right?(table_name)
      grant_access?('index', table_name)  
    end
    
    def has_show_right?(table_name)
      grant_access?('show', table_name)  
    end
    
    def has_create_right?(table_name)
      grant_access?('create', table_name)  
    end
    
    def has_update_right?(table_name)
      grant_access?('update', table_name)  
    end
    
    def has_destroy_right?(table_name)
      grant_access?('destroy', table_name)
    end
    
    #allow to activate/deactivate a contract
    def has_activate_right?(table_name)
      grant_access?('activate', table_name)
    end
  end
end

app/helpers/bank_accountx/accounts_helper.rb
module BankAccountx
  module AccountsHelper
  end
end

app/helpers/bank_accountx/application_helper.rb
module BankAccountx
  module ApplicationHelper
  end
end

app/views/bank_accountx/accounts/_form.html.erb
<%= simple_form_for @account do |f| %>    
 
  <%= f.input :account_name, :label => "AccountName:" %> 
  <%= f.input :account_num, :label => "Account#:" %>
  <%= f.input :bank_name, :label => "BankName:" %>  
  <%= f.input :active, :collection => yes_no_cn(), :label => 'Active:' %> 
  <%= f.input :brief_note, :label => "BriefNote:" %>  
  
  <%= f.button :submit, 'Save' %>  
<% end %> 

app/views/bank_accountx/accounts/_form_new.html.erb
<%= simple_form_for @account do |f| %>    
 
  <%= f.input :account_name, :label => "AccountName:" %> 
  <%= f.input :account_num, :label => "Account#:" %>
  <%= f.input :bank_name, :label => "BankName:" %>   
  <%= f.input :brief_note, :label => "BriefNote:" %>  
  
  <%= f.button :submit, 'Save' %>  
<% end %> 

app/views/bank_accountx/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/bank_accountx/accounts/create.html.erb</p>

app/views/bank_accountx/accounts/edit.html.erb
<div id="main_body">
<h1>Edit Bank Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>
</div>

app/views/bank_accountx/accounts/edit.js.erb
$("<%= escape_javascript render(:file => 'bank_accountx/accounts/edit.html.erb') %>").insertAfter('#new_log_link');
$('#new_log_link').hide();
$('#close').hide();

app/views/bank_accountx/accounts/index.html.erb
<div id="main_body">
  <h1>Bank Accounts</h1>
  <table>
    <tr>
      <th>CreateDate</th>
      <th>AccountName</th>
      <th>AccountNumber</th>
      <th>BankName</th> 
      <th>Active</th>     
      <th>UpdatedBy</th>
      <th>BriefNote</th>
      <th></th>
    </tr>

    <% @accounts.each do |r| %>
        <tr>
          <td><%= (r.created_at + 8.hours).strftime("%Y/%m/%d")%></td>
          <td><%= r.account_name %></td>
          <td><%= r.account_num %></td>         
          <td><%= r.bank_name %></td>
          <td><%= r.active %></td>
          <td><%= r.last_updated_by.name %></td>
          <td><%= r.brief_note %></td>
          <td><%= link_to 'Edit', edit_account_path(r, :format => :js), :remote => true if has_update_right?('bank_accountx_accounts') %></td>
        </tr>
    <% end %>

  </table>

  <%= link_to 'Back', SUBURI + "/authentify/view_handler?index=0", :id => 'close' %>&nbsp; |&nbsp;
  <%= link_to "New Bank Account", new_account_path(:format => :js), :remote => true, :id => 'new_log_link' if has_create_right?('bank_accountx_accounts') %>

</div>

app/views/bank_accountx/accounts/new.html.erb
<div id="main_body">
<h1>New Bank Account</h1>

<%= render 'form_new' %>

<%= link_to 'Back', accounts_path %>
</div>

app/views/bank_accountx/accounts/new.js.erb
$("<%= escape_javascript render(:file => 'bank_accountx/accounts/new.html.erb') %>").insertAfter('#new_log_link');
$('#new_log_link').hide();
$('#close').hide();

app/views/bank_accountx/accounts/update.html.erb
<h1>Accounts#update</h1>
<p>Find me in app/views/bank_accountx/accounts/update.html.erb</p>

app/views/layouts/bank_accountx/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BankAccountx</title>
  <%= stylesheet_link_tag    "bank_accountx/application", :media => "all" %>
  <%= javascript_include_tag "bank_accountx/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>